site_name: Jeffrey the Reader - 一个爱读英文原版书的人
site_url: https://reader.gypsop.tech
theme:
  name: material
  palette:
    primary: teal
    accent: cyan
  language: zh
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Gypsop/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/gypsop.zhu/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xiaoshengzhu/
copyright: Copyright &copy; 2016 - 2025 Xiaosheng (Jeffrey) ZHU
nav:
  - 主页: index.md
  - 附录: 
    - 关于: about.md